import { Assistant } from "next/font/google";
import Hero from "./components/hero";
import "./globals.css";

const assistant = Assistant({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={assistant.className}>
        <Hero/>
        {children}
      </body>
    </html>
  );
}
